# Generated by Django 4.2 on 2024-04-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'permissions': [('view_customuserinfo', 'Can view user information')]},
        ),
    ]
