# Generated by Django 4.2 on 2024-04-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
    ]
